name = "azure-quiz-cloud"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# فرانت استاتیک
[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"

# D1 — بدون database_id تا در اولین deploy ساخته شود (یا بعداً id را بگذارید)
[[d1_databases]]
binding = "DB"
database_name = "azure-quiz-db"

[vars]
ADMIN_NATIONAL_IDS = "1274829860"
