-- seed data
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('1274829860','مهدی','میرزاپور','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('0012345678','مهدی','جبارزارع','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('0012345680','سارا','احمدی','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('0012345681','رضا','کریمی','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('0012345682','فاطمه','محمدی','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('2062267584','سید علی','سید میرزاپور','');
INSERT OR IGNORE INTO members (national_id, first_name, last_name, phone) VALUES ('9999999999','عزیزدل','محمدقاسمی جون','');
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ اصلی برای لینک در HTML چیست؟','<link>','<a>','<href>','<url>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام ویژگی برای آدرس لینک استفاده می‌شود؟','src','href','link','url',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ تصویر در HTML؟','<img>','<image>','<pic>','<photo>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام ویژگی مسیر تصویر را مشخص می‌کند؟','href','src','path','url',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','برای ایجاد لیست شماره‌دار از چه تگی استفاده می‌شود؟','<ul>','<ol>','<li>','<list>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ پاراگراف؟','<p>','<para>','<text>','<paragraph>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام تگ عنوان سطح ۱ است؟','<h1>','<title>','<header>','<head>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','برای استایل درون‌خطی از کدام ویژگی استفاده می‌شود؟','class','id','style','css',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام سلکتور CSS برای id است؟','.name','#name','name','*name',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام سلکتور CSS برای class است؟','.name','#name','name','@name',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','ویژگی CSS برای رنگ متن؟','background','color','font-color','text-color',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','ویژگی CSS برای رنگ پس‌زمینه؟','color','background-color','bg','fill',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','واحد نسبی در CSS؟','px','em','cm','mm',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام display باعث می‌شود عنصر مثل بلاک رفتار کند؟','inline','block','flex','none',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','برای مخفی کردن عنصر از چه مقداری برای display استفاده می‌شود؟','hidden','none','invisible','hide',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ جدول؟','<table>','<tab>','<grid>','<tr>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ ردیف جدول؟','<td>','<tr>','<th>','<row>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ سلول جدول؟','<td>','<tr>','<cell>','<th>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام تگ فرم ورودی متن ایجاد می‌کند؟','<input>','<text>','<field>','<form>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','ویژگی type برای دکمه submit؟','button','submit','send','ok',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام تگ لیست بدون شماره است؟','<ol>','<ul>','<dl>','<list>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ شکستن خط؟','<br>','<break>','<lb>','<hr>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ خط افقی؟','<br>','<hr>','<line>','<border>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام ویژگی HTML5 برای ویدیو استفاده می‌شود؟','<media>','<video>','<movie>','<film>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','ویژگی CSS برای فاصله بیرونی؟','padding','margin','border','spacing',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','ویژگی CSS برای فاصله درونی؟','padding','margin','border','spacing',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام position عنصر را نسبت به viewport ثابت می‌کند؟','relative','absolute','fixed','static',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','Flexbox با چه display فعال می‌شود؟','block','flex','grid','inline',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام ویژگی HTML برای دسترسی‌پذیری متن جایگزین تصویر است؟','title','alt','desc','label',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ معنایی برای ناوبری؟','<nav>','<menu>','<header>','<aside>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام تگ اسکریپت جاوااسکریپت را در HTML قرار می‌دهد؟','<js>','<script>','<javascript>','<code>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','فایل CSS خارجی با چه تگی لینک می‌شود؟','<style>','<link>','<css>','<import>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام مقدار box-sizing شامل padding و border در عرض می‌شود؟','content-box','border-box','padding-box','full-box',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','واحد viewport width؟','vw','vh','vmin','px',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام شبه‌کلاس برای هاور ماوس است؟',':active',':hover',':focus',':visited',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ HTML5 برای بخش اصلی محتوا؟','<section>','<main>','<article>','<content>',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام ویژگی برای باز کردن لینک در تب جدید؟','target=''_blank''','new=''tab''','blank=''true''','window=''new''',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','رنگ در CSS با هگز چگونه نوشته می‌شود؟','#RGB','rgb()','color()','hex()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','کدام display عنصر را از جریان خارج ولی فضا نگه می‌دارد؟','none','hidden','visibility:hidden','opacity:0',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('HTML & CSS','تگ meta charset معمولاً چه مقداری دارد؟','utf-8','ascii','latin1','iso',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام کلمه برای تعریف تابع در Python استفاده می‌شود؟','function','func','def','define',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام نوع داده در Python تغییرپذیر (mutable) است؟','tuple','list','str','int',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی print(type([])) چیست؟','<class ''list''>','<class ''tuple''>','<class ''dict''>','<class ''set''>',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای ایجاد کامنت تک‌خطی در Python از چه چیزی استفاده می‌شود؟','//','/* */','#','--',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام عملگر برای توان استفاده می‌شود؟','^','**','pow','^^',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','متد append روی کدام نوع داده کار می‌کند؟','tuple','str','list','int',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی len(''Python'') چیست؟','5','6','7','8',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام ساختار برای حلقه تکرار استفاده می‌شود؟','repeat','for','loop','each',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای مدیریت استثنا از کدام کلمات کلیدی استفاده می‌شود؟','try/except','catch/throw','error/handle','do/catch',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام تابع برای دریافت ورودی کاربر استفاده می‌شود؟','input()','read()','scan()','get()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','مقدار پیش‌فرض پارامتر در تعریف تابع چگونه مشخص می‌شود؟','def f(x=1)','def f(x:1)','def f(x->1)','def f(x:=1)',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام متد رشته را به لیست تبدیل می‌کند؟','split()','join()','divide()','part()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی bool([]) چیست؟','True','False','None','Error',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای تعریف کلاس از کدام کلمه استفاده می‌شود؟','class','struct','object','type',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام ماژول برای کار با تاریخ و زمان استاندارد است؟','time','datetime','date','calendar',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی 3 // 2 در Python 3 چیست؟','1.5','1','2','1.0',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام ساختار داده کلید-مقدار دارد؟','list','tuple','dict','set',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای باز کردن فایل از کدام تابع استفاده می‌شود؟','open()','file()','read()','load()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام کلمه کلیدی برای ارث‌بری استفاده می‌شود؟','extends','inherits','class Child(Parent)','derive',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی ''a'' * 3 چیست؟','aaa','a3','aa','Error',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام متد آخرین عنصر لیست را حذف و برمی‌گرداند؟','remove()','pop()','delete()','cut()',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای نصب پکیج از چه ابزاری استفاده می‌شود؟','npm','pip','apt','yarn',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام عبارت شرطی صحیح است؟','if x = 1:','if x == 1:','if x := 1:','if x === 1:',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی list(range(3)) چیست؟','[0,1,2]','[1,2,3]','[0,1,2,3]','[1,2]',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام کلمه برای تعریف تابع بی‌نام استفاده می‌شود؟','lambda','anon','def','func',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','ماژول استاندارد برای تولید عدد تصادفی؟','random','rand','numpy','math',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام عملگر عضویت است؟','in','has','contains','inside',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی type(None) چیست؟','NoneType','null','void','None',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای ایجاد مجموعه (set) از چه نشانه‌ای استفاده می‌شود؟','[]','()','{}','<>',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام متد همه عناصر لیست را پاک می‌کند؟','clear()','empty()','remove()','delete()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی 10 % 3 چیست؟','3','1','0','10',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام ساختار برای تعریف تاپل با یک عنصر صحیح است؟','(1)','(1,)','[1]','{1}',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای import کردن ماژول از چه کلمه‌ای استفاده می‌شود؟','include','import','require','using',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام تابع طول قابل‌پیمایش را برمی‌گرداند؟','size()','len()','length()','count()',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی bool(0) چیست؟','True','False','0','None',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام متد رشته را از چپ و راست trim می‌کند؟','strip()','trim()','clean()','cut()',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','برای تعریف متغیر سراسری داخل تابع از چه کلمه‌ای استفاده می‌شود؟','global','public','static','outer',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام پروتکل برای iteration استفاده می‌شود؟','__iter__','__next__','هر دو','هیچ‌کدام',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','خروجی ''Hello''[1] چیست؟','H','e','l','o',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('Python','کدام کتابخانه استاندارد برای JSON است؟','json','simplejson','ujson','pickle',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی زمانی جستجوی خطی در بدترین حالت؟','O(1)','O(log n)','O(n)','O(n²)',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی زمانی جستجوی باینری؟','O(n)','O(log n)','O(n log n)','O(1)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام ساختار داده FIFO است؟','Stack','Queue','Tree','Graph',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام ساختار داده LIFO است؟','Queue','Stack','Heap','List',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','مرتب‌سازی حبابی در بدترین حالت چه پیچیدگی دارد؟','O(n)','O(n log n)','O(n²)','O(log n)',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام الگوریتم مرتب‌سازی معمولاً O(n log n) است؟','Bubble Sort','Merge Sort','Insertion Sort','Selection Sort',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','در درخت دودویی جستجو، فرزند چپ نسبت به والد؟','بزرگ‌تر','کوچک‌تر','مساوی','نامشخص',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','ارتفاع درخت با یک گره؟','0','1','2','-1',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام پیمایش درخت به صورت ریشه-چپ-راست است؟','Inorder','Preorder','Postorder','Level-order',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیمایش Inorder در BST چه ترتیبی می‌دهد؟','نزولی','صعودی','تصادفی','سطح‌به‌سطح',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام ساختار برای پیاده‌سازی recursion طبیعی است؟','Queue','Stack','Heap','Graph',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی دسترسی به عنصر آرایه با ایندکس؟','O(n)','O(1)','O(log n)','O(n²)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام الگوریتم برای یافتن کوتاه‌ترین مسیر در گراف وزن‌دار غیرمنفی استفاده می‌شود؟','DFS','BFS','Dijkstra','Kruskal',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','BFS از چه ساختاری استفاده می‌کند؟','Stack','Queue','Heap','Tree',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','DFS از چه ساختاری استفاده می‌کند؟','Queue','Stack','Array','Set',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','در همسایگی گراف، درجه گره یعنی؟','تعداد یال‌های متصل','وزن گره','ارتفاع','سطح',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام مرتب‌سازی درجا (in-place) نیست؟','Quick Sort','Merge Sort','Heap Sort','Insertion Sort',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','بدترین حالت Quick Sort؟','O(n log n)','O(n)','O(n²)','O(log n)',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام داده ساختار برای پیاده‌سازی Priority Queue مناسب است؟','Array','Linked List','Heap','Stack',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی درج در ابتدای Linked List؟','O(n)','O(1)','O(log n)','O(n²)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام الگوریتم حریصانه برای درخت پوشای کمینه است؟','Dijkstra','Prim','Bellman-Ford','Floyd',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','مفهوم Divide and Conquer یعنی؟','تقسیم و حل','جستجوی خطی','مرتب‌سازی حبابی','پیمایش سطحی',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','در جدول هش، برخورد (collision) یعنی؟','دو کلید یکسان','دو کلید به یک سطل','پر شدن جدول','حذف کلید',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام ساختار برای نمایش سلسله‌مراتب مناسب است؟','Array','Queue','Tree','Stack',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی فضایی recursion عمق n در حالت معمول؟','O(1)','O(n)','O(n²)','O(log n)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام الگوریتم برای تشخیص دور در گراف جهت‌دار استفاده می‌شود؟','BFS','DFS با رنگ‌آمیزی','Dijkstra','Binary Search',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','Big-O برای ثابت بودن زمان؟','O(n)','O(1)','O(log n)','O(n!)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام مرتب‌سازی پایدار (stable) است؟','Quick Sort','Heap Sort','Merge Sort','Selection Sort',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','در صف دو سر (Deque) چه عملیاتی ممکن است؟','فقط از جلو','فقط از عقب','از هر دو طرف','هیچ',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی ساخت Heap از n عنصر؟','O(n log n)','O(n)','O(log n)','O(n²)',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام ساختار برای Undo مناسب است؟','Queue','Stack','Tree','Graph',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','الگوریتم Binary Search روی چه داده‌ای کار می‌کند؟','نامرتب','مرتب','دوطرفه','تصادفی',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','تعداد یال‌های درخت با n گره؟','n','n-1','n+1','2n',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام پیمایش سطح‌به‌سطح است؟','DFS','BFS','Inorder','Postorder',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','مفهوم Dynamic Programming؟','تقسیم مسئله به زیرمسئله‌های هم‌پوشان','جستجوی تصادفی','مرتب‌سازی','هش',1);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','پیچیدگی زمانی Selection Sort؟','O(n)','O(n log n)','O(n²)','O(log n)',3);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام داده ساختار دسترسی تصادفی سریع دارد؟','Linked List','Array','Stack','Queue',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','در گراف بدون وزن، کوتاه‌ترین مسیر با؟','Dijkstra','BFS','DFS','Prim',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','کدام الگوریتم مرتب‌سازی بر اساس مقایسه نیست؟','Merge Sort','Counting Sort','Quick Sort','Heap Sort',2);
INSERT INTO questions (lesson, question, option1, option2, option3, option4, correct) VALUES ('مبانی الگوریتم','هدف از تحلیل پیچیدگی الگوریتم؟','اندازه‌گیری زمان و فضای مورد نیاز','زیبایی کد','تعداد خطوط','نام متغیرها',1);